apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kubernetes-prometheus/prometheus-deployment.yaml
- kubernetes-prometheus/config-map.yaml
- kubernetes-prometheus/clusterRole.yaml
- kubernetes-prometheus/prometheus-service.yaml
- kubernetes-grafana/grafana-deployment.yaml
- kubernetes-grafana/grafana-datasource-config.yaml
- kubernetes-grafana/secret.yaml
- kubernetes-grafana/service.yaml
- kubernetes-grafana/volume.yaml
