apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- database/mysql-secret.yaml
- database/mysql-service.yaml
- database/mysql-deployment.yaml
- app-wordpress/wordpress-service.yaml
- app-wordpress/wordpress-deployment.yaml
- pvc/mysql-pvc.yaml
- pvc/wordpress-pvc.yaml

